### PR TITLE
Pw/explaintrussjson

### PR DESCRIPTION
**Pull request by pitipatw**
### Summary

A short summary of the changes in this PR.

**Highlights**:
1. JSON file explanation
2. Remove lines that relate to visualization

### What type of change is this?

- [ ] Bug fix in a **backwards-compatible** manner.
- [ ] New feature in a **backwards-compatible** manner.
- [ ] Breaking change: bug fix or new feature that involve incompatible API changes.
- [x] Other (e.g. doc update, configuration, etc)

### Checklist

- [ ] I ran all tests on my computer and it's all green (i.e. `] test`).
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by pitipatw** [comment]
I commented those lines out.

**Comment by mohamed82008** [comment]
I merged master into this. You will need to do `git pull` from your local branch before you push other changes to this PR.

**Review by pitipatw — COMMENTED** [review]
I thought I accidentally commented the line.

**Comment by pitipatw** [comment]
> I merged master into this. You will need to do `git pull` from your local branch before you push other changes to this PR.

You mean pull the master branch to my local branch then create a new PR from the branch?

**Comment by mohamed82008** [comment]
No just pull from the `pw/explaintrussjson` branch on GitHub (which I modified) to your local `pw/explaintrussjson` branch (to sync them) before you make further changes locally and then push them to the GitHub branch which will update this PR.

**Comment by mohamed82008** [comment]
If that doesn't make sense, we can discuss it on a call.

**Comment by yijiangh** [comment]
Close since the doc is included in https://github.com/JuliaTopOpt/TopOpt.jl/pull/152/commits/c01a05e11554a82d14df99aa47a716fc28002146 as a part of #152 .

**Pull request closed without merging**
