### PR TITLE
Debug truss_stress.jl coupled variable R

### PR DESCRIPTION
**Pull request by pitipatw**
### Summary

A short summary of the changes in this PR.

**Highlights**:
1. on truss_stress.jl line 35 add copy(R) to uncouple the  variables

### What type of change is this?

- [x] Bug fix in a **backwards-compatible** manner.
- [ ] New feature in a **backwards-compatible** manner.
- [ ] Breaking change: bug fix or new feature that involve incompatible API changes.
- [ ] Other (e.g. doc update, configuration, etc)

### Checklist

- [x] I ran all tests on my computer and it's all green (i.e. `] test`).
- [x] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by pitipatw** [comment]
I hope this work :)

**Comment by yijiangh** [comment]
Could you please add a test file with your 3-member truss to compare against hand-derived values?

**Comment by pitipatw** [comment]
Will do!

**Comment by pitipatw** [comment]
I added the test file in the "test" folder.

**Comment by pitipatw** [comment]
> @pitipatw Could you please add a test file with your 3-member truss to compare against hand-derived values?

Please let me know if I should add to the test folder or somewhere else.

**Comment by mohamed82008** [comment]
You have to include the new test file in the `runtests.jl` file.

**Comment by pitipatw** [comment]
The JSON file too?

**Comment by mohamed82008** [comment]
You can put the file in the same directory. But only include the Julia file in runtests.Jo

**Comment by yijiangh** [comment]
Also, I think it makes a lot of sense to merge your work on the JSON documentation into this one PR here. Shall we do that?

**Comment by pitipatw** [comment]
I updated the test file, however, when I run the `runtest.jl` ,  it says Functions/test_common_fns.jl is broken. 

Mine pass successfully.

**Comment by pitipatw** [comment]
> Also, I think it makes a lot of sense to merge your work on the JSON documentation (#148) into this one PR here. Shall we do that?

Isn't it already come with the commits in this PR?

**Comment by yijiangh** [comment]
Close #138

**Pull request merged**
